# namespace_catalog.py — RT.g() namespace に載るキー名の一覧（docs 参照用）

from __future__ import annotations

from game_state import PLAY_STATE_FIELDS

# install_assets → load_all_assets の dict キー + install_assets で付与する色定数
ASSET_IMAGE_AND_FONT_KEYS = (
    "bg_far",
    "bg_mid",
    "bg_front",
    "boss5_bg_far",
    "boss5_bg_mid",
    "boss5_bg_front",
    "extra_bg_far",
    "extra_bg_mid",
    "extra_bg_front",
    "extra_boss_images",
    "extra_funnel_img",
    "notice_img",
    "next_screen_img",
    "next_screen2_img",
    "title_img",
    "warning_img",
    "gameover_img",
    "ending_img",
    "extra_ending_slides",
    "fin_script_font",
    "diff_select_bg",
    "config_keyboard_bg",
    "config_controller_bg",
    "diff_imgs",
    "player_images",
    "life_icon_img",
    "bullet_img",
    "laser_img",
    "shield_img",
    "enemy_images",
    "enemy_bullet_img",
    "homing_bullet_img",
    "turret_top_img",
    "turret_bottom_img",
    "boss_bullet_img_01",
    "boss_bullet_img_02",
    "boss_bullet_img_03",
    "boss_specific_bullet_imgs",
    "boss3_ufo_img",
    "boss_bullet_img",
    "boss_shield_img",
    "boss_shield_img2",
    "midboss_img1",
    "midboss_img1b",
    "midboss_img2",
    "midboss_img2b",
    "midboss_img3",
    "midboss_img3b",
    "boss2_fish_img",
    "midboss4_body_img",
    "midboss4_body_src",
    "midboss4_body_d",
    "midboss4_body_e",
    "midboss4_body_f",
    "boss4_overlay_top_img",
    "boss4_overlay_bottom_img",
    "midboss5_images",
    "boss_ripple_base_img",
    "boss1_ripple_img",
    "meteor_img",
    "meteor_small_img",
    "support_fighter_images",
    "power_weapon_img",
    "power_laser_charge_img",
    "power_shield_img",
    "power_speed_img",
    "power_super_img",
    "power_1up_img",
    "font",
    "font2",
    "font_hud_sm",
    "hud_font",
    "hp_bar_font",
    "big_font",
    "noto_font_path",
)

COLOR_KEYS = (
    "WHITE",
    "RED",
    "GREEN",
    "CYAN",
    "YELLOW",
    "ORANGE",
    "DARK_ORANGE",
    "BLUE",
    "LIGHT_BLUE",
    "GRAY",
    "DARK_GRAY",
    "BLACK",
)

# audio.load_all_sfx → install_sfx
SFX_KEYS = (
    "shot_sound",
    "explosion_sound",
    "warning_sound",
    "boss_shield_hit_sound",
    "boss_shield_break_sound",
    "player_shield_hit_sound",
    "player_shield_break_sound",
    "item_weapon_sound",
    "item_shield_sound",
    "item_speed_sound",
    "launch_sound",
    "beam_sound",
    "ems_get_sound",
    "ems_use_sound",
    "laser_warning_sound",
    "difficulty_select_sound",
    "difficulty_confirm_sound",
    "title_cheat_sound",
    "score_tick_sound",
    "chain_milestone_sound",
    "ripple_sound",
    "boss_special_alert_sound",
    "boss5_gravity_sound",
    "boss5_meteo3_sound",
    "boss5_meteo1_sound",
    "boss5_silence_sound",
    "boss5_suck_sound",
    "ending_screen_sound",
    "support_arrive_sound",
    "extra_boss_enter_sound",
    "extra_boss_beam_charge_sound",
    "extra_boss_beam_fire_sound",
    "extra_funnel_shot_sound",
)

# game_registry.install_game_registry
REGISTRY_CALLABLE_KEYS = (
    "spawn_enemy_bullet",
    "spawn_enemy_laser",
    "spawn_boss5_red_laser",
    "spawn_boss5_ripple",
    "spawn_boss5_meteor",
    "enemy_bullet_hit_rect",
    "update_enemy_bullets_frame",
    "update_meteors_frame",
    "draw_scroll",
    "draw_text_with_shadow",
    "key_label",
    "pad_label",
)

PLAY_STATE_GLOBAL_NAMES = PLAY_STATE_FIELDS
